export default () => ({
  apiExampleData: [],
  socket: {
    isConnected: false,
    message: '',
    reconnectError: false,
  },
  mainItem: [],
  nowMainItem: [],
  nowFiveMoney: [],
  nowVolumeMoney: [],
  nowNewPrice: [],
  historyPrice: [],
  kLineData: [],
  chartData: [],
  clickItemId: 'TXF',
  itemName: '台指期',
  chartType: '',
  userInfo: [],
  commidyArray: [],
  loading: true,
})
